common:
    arch: FaceFeatherNetMFT_v3
    workers: 8
    batch_size: 64
    epochs: 180
    policy: "step"
    base_lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
    print_freq: 10
    save_path: checkpoints/FaceFeatherNetA_mutift_nir_rgb_210607
