common:
    arch: resnet34
    workers: 4
    batch_size: 64
    epochs: 180
    policy: "step"
    base_lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
    print_freq: 10
    save_path: checkpoints/ResNet34_0616
